/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as BecomeAgentRouteImport } from './routes/become-agent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAgentRoute = BecomeAgentRouteImport.update({
  id: '/become-agent',
  path: '/become-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-agent': typeof BecomeAgentRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/store/$slug': typeof StoreSlugRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/track/': typeof TrackIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-agent': typeof BecomeAgentRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/store/$slug': typeof StoreSlugRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/track': typeof TrackIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-agent': typeof BecomeAgentRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/store/$slug': typeof StoreSlugRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/track/': typeof TrackIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-agent'
    | '/bundles'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/store/$slug'
    | '/track/$orderId'
    | '/track/'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-agent'
    | '/bundles'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/store/$slug'
    | '/track/$orderId'
    | '/track'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-agent'
    | '/bundles'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/store/$slug'
    | '/track/$orderId'
    | '/track/'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeAgentRoute: typeof BecomeAgentRoute
  BundlesRoute: typeof BundlesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  StoreSlugRoute: typeof StoreSlugRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  TrackIndexRoute: typeof TrackIndexRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-agent': {
      id: '/become-agent'
      path: '/become-agent'
      fullPath: '/become-agent'
      preLoaderRoute: typeof BecomeAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeAgentRoute: BecomeAgentRoute,
  BundlesRoute: BundlesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  StoreSlugRoute: StoreSlugRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  TrackIndexRoute: TrackIndexRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
